[project]
name = "lrbc-api"
version = "0.1.0"
description = "LRBC website API functions"
requires-python = ">=3.12"
dependencies = [
    "google-api-python-client==2.188.0",
    "google-auth==2.47.0",
]
